package tile;

import java.util.*;

public class TileManager {
    public static HashMap<String, Tile> tile;

    public TileManager() {
        tile = new HashMap<String, Tile>();
        loadTile();
    }

    public void loadTile(){
        addTile("water");
        addTile("sand");
        addTile("grass01");
        addTile("grass02");
        addTile("grass03");
        addTile("grass04");
        addTile("grass05");
        addTile("grass06");
        addTile("grass07");
        addTile("grass08");
        addTile("road01");
        addTile("road02");
        addTile("road03");
        addTile("road04");
        addTile("road05");
        addTile("road06");
        addTile("road07");
        addTile("road08");
        addTile("road");
        addTile("grass_corner01");
        addTile("grass_corner02");
        addTile("grass_corner03");
        addTile("grass_corner04");
        addTile("grass_corner05");
        addTile("grass_corner06");
        addTile("grass_corner07");
        addTile("grass_corner08");
        addTile("level_floor01");
        addTile("level_floor02");
        addTile("level_floor03");
        addTile("brick01");
        addTile("brick02");
        addTile("port01");
        addTile("port02");
        addTile("player_house_wall01_1");
        addTile("player_house_wall01_2");
        addTile("player_house_wall01_3");
        addTile("player_house_wall02_1");
        addTile("player_house_wall02_2");
        addTile("player_house_wall02_3");
        addTile("player_house_roof01");
        addTile("player_house_roof02");
        addTile("player_house_roof03");
        addTile("player_house_roof04");
        addTile("player_house_floor01");
        addTile("player_house_floor02");
        addTile("stone_house_wall01_1");
        addTile("stone_house_wall01_2");
        addTile("stone_house_wall01_3");
        addTile("stone_house_wall02_1");
        addTile("stone_house_wall02_2");
        addTile("stone_house_wall02_3");
        addTile("stone_house_roof01");
        addTile("stone_house_roof02");
        addTile("stone_house_roof03");
        addTile("stone_house_roof04");
        addTile("shop_wall01_1");
        addTile("shop_wall01_2");
        addTile("shop_wall01_3");
        addTile("shop_wall02_1");
        addTile("shop_wall02_2");
        addTile("shop_wall02_3");
        addTile("shop_roof01");
        addTile("shop_roof02");
        addTile("shop_roof03");
        addTile("shop_roof04");
        addTile("pool01_1");
        addTile("pool01_2");
        addTile("pool01_3");
        addTile("pool02_1");
        addTile("pool02_2");
        addTile("pool02_3");
        addTile("pool03_1");
        addTile("pool03_2");
        addTile("pool03_3");
        addTile("bush");
        addTile("bench01");
        addTile("bench02");
        addTile("bench03");
        addTile("clothes_line01_1");
        addTile("clothes_line01_2");
        addTile("clothes_line01_3");
        addTile("clothes_line01_4");
        addTile("clothes_line02_1");
        addTile("clothes_line02_2");
        addTile("clothes_line02_3");
        addTile("clothes_line02_4");
        addTile("camber01");
        addTile("camber02");
        addTile("camber03");
        addTile("camber04");
        addTile("camber05");
        addTile("camber06");
        addTile("table01_1");
        addTile("table01_2");
        addTile("table01_3");
        addTile("table02_1");
        addTile("table02_2");
        addTile("table02_3");
        addTile("table03_1");
        addTile("table03_2");
        addTile("table03_3");
        addTile("jar01");
        addTile("jar02");
        addTile("fence_x");
        addTile("fence_y");
        addTile("fence_top_left");
        addTile("fence_top_right");
        addTile("fence_bot_right");
        addTile("fence_bot_left");
        addTile("fence_end_left");
        addTile("fence_end_right");
        addTile("fence_end_top");
        addTile("stair_top_left");
        addTile("stair_top_right");
        addTile("stair_mid_left");
        addTile("stair_mid_cen");
        addTile("stair_mid_right");
        addTile("stair_bot_left");
        addTile("stair_bot_cen");
        addTile("stair_bot_right");
        addTile("player_house_door01");
        addTile("player_house_door02");
        addTile("straws01");
        addTile("straws02");
        addTile("straws03");
        addTile("straws04");
        addTile("straws05");
        addTile("straws06");
        addTile("shop_door01");
        addTile("shop_door02");
        addTile("stone_house_door01");
        addTile("stone_house_door02");
        addTile("stone_house_tag");
        addTile("barrel01");
        addTile("barrel02");
        addTile("barrel03");
        addTile("barrel04");
        addTile("barrel05");
        addTile("barrel06");
        addTile("window01");
        addTile("window02");
        addTile("mission_board01");
        addTile("mission_board02");
        addTile("mission_board03");
        addTile("mission_board04");
        addTile("sign01");
        addTile("sign02");
        addTile("sign03");
        addTile("post_box");
        addTile("not_use");
        addTile("pass");
    }

    private void addTile(String filename) {
        tile.put(filename, new Tile(filename));
    }

    public static Tile getTile(String name) {
        return tile.get(name);
    }

    public static Tile getTileByNumber(int tileNumber){
        return switch (tileNumber) {
            case 2054 -> TileManager.getTile("water");
            case 6 -> TileManager.getTile("sand");
            case 75 -> TileManager.getTile("grass01");
            case 76 -> TileManager.getTile("grass02");
            case 77 -> TileManager.getTile("grass03");
            case 78 -> TileManager.getTile("grass04");
            case 83 -> TileManager.getTile("grass05");
            case 84 -> TileManager.getTile("grass06");
            case 85 -> TileManager.getTile("grass07");
            case 86 -> TileManager.getTile("grass08");
            case 1 -> TileManager.getTile("road01");
            case 52 -> TileManager.getTile("road02");
            case 33 -> TileManager.getTile("road03");
            case 4 -> TileManager.getTile("road04");
            case 21 -> TileManager.getTile("road05");
            case 35 -> TileManager.getTile("road06");
            case 31 -> TileManager.getTile("road07");
            case 23 -> TileManager.getTile("road08");
            case 14 -> TileManager.getTile("road");
            case 89 -> TileManager.getTile("grass_corner01");
            case 80 -> TileManager.getTile("grass_corner02");
            case 73 -> TileManager.getTile("grass_corner03");
            case 82 -> TileManager.getTile("grass_corner04");
            case 88 -> TileManager.getTile("grass_corner05");
            case 72 -> TileManager.getTile("grass_corner06");
            case 74 -> TileManager.getTile("grass_corner07");
            case 90 -> TileManager.getTile("grass_corner08");
            case 104 -> TileManager.getTile("level_floor01");
            case 105 -> TileManager.getTile("level_floor02");
            case 106 -> TileManager.getTile("level_floor03");
            case 298 -> TileManager.getTile("brick01");
            case 322 -> TileManager.getTile("brick02");
            case 225 -> TileManager.getTile("port01");
            case 233 -> TileManager.getTile("port02");
            case 496 -> TileManager.getTile("player_house_wall01_1");
            case 497 -> TileManager.getTile("player_house_wall01_2");
            case 498 -> TileManager.getTile("player_house_wall01_3");
            case 504 -> TileManager.getTile("player_house_wall02_1");
            case 505 -> TileManager.getTile("player_house_wall02_2");
            case 506 -> TileManager.getTile("player_house_wall02_3");
            case 560 -> TileManager.getTile("player_house_roof01");
            case 568 -> TileManager.getTile("player_house_roof02");
            case 576 -> TileManager.getTile("player_house_roof03");
            case 584 -> TileManager.getTile("player_house_roof04");
            case 366 -> TileManager.getTile("player_house_floor01");
            case 358 -> TileManager.getTile("player_house_floor02");
            case 448 -> TileManager.getTile("stone_house_wall01_1");
            case 449 -> TileManager.getTile("stone_house_wall01_2");
            case 450 -> TileManager.getTile("stone_house_wall01_3");
            case 456 -> TileManager.getTile("stone_house_wall02_1");
            case 457 -> TileManager.getTile("stone_house_wall02_2");
            case 458 -> TileManager.getTile("stone_house_wall02_3");
            case 564 -> TileManager.getTile("stone_house_roof01");
            case 572 -> TileManager.getTile("stone_house_roof02");
            case 580 -> TileManager.getTile("stone_house_roof03");
            case 588 -> TileManager.getTile("stone_house_roof04");
            case 528 -> TileManager.getTile("shop_wall01_1");
            case 529 -> TileManager.getTile("shop_wall01_2");
            case 530 -> TileManager.getTile("shop_wall01_3");
            case 536 -> TileManager.getTile("shop_wall02_1");
            case 537 -> TileManager.getTile("shop_wall02_2");
            case 538 -> TileManager.getTile("shop_wall02_3");
            case 561 -> TileManager.getTile("shop_roof01");
            case 569 -> TileManager.getTile("shop_roof02");
            case 577 -> TileManager.getTile("shop_roof03");
            case 585 -> TileManager.getTile("shop_roof04");
            case 928 -> TileManager.getTile("pool01_1");
            case 929 -> TileManager.getTile("pool01_2");
            case 930 -> TileManager.getTile("pool01_3");
            case 936 -> TileManager.getTile("pool02_1");
            case 937 -> TileManager.getTile("pool02_2");
            case 938 -> TileManager.getTile("pool02_3");
            case 944 -> TileManager.getTile("pool03_1");
            case 945 -> TileManager.getTile("pool03_2");
            case 946 -> TileManager.getTile("pool03_3");
            case 40 -> TileManager.getTile("bush");
            case 848 -> TileManager.getTile("bench01");
            case 849 -> TileManager.getTile("bench02");
            case 850 -> TileManager.getTile("bench03");
            case 262 -> TileManager.getTile("clothes_line01_1");
            case 263 -> TileManager.getTile("clothes_line01_2");
            case 270 -> TileManager.getTile("clothes_line01_3");
            case 271 -> TileManager.getTile("clothes_line01_4");
            case 278 -> TileManager.getTile("clothes_line02_1");
            case 279 -> TileManager.getTile("clothes_line02_2");
            case 286 -> TileManager.getTile("clothes_line02_3");
            case 287 -> TileManager.getTile("clothes_line02_4");
            case 909 -> TileManager.getTile("camber01");
            case 917 -> TileManager.getTile("camber02");
            case 925 -> TileManager.getTile("camber03");
            case 933 -> TileManager.getTile("camber04");
            case 941 -> TileManager.getTile("camber05");
            case 949 -> TileManager.getTile("camber06");
            case 717 -> TileManager.getTile("table01_1");
            case 718 -> TileManager.getTile("table01_2");
            case 719 -> TileManager.getTile("table01_3");
            case 725 -> TileManager.getTile("table02_1");
            case 726 -> TileManager.getTile("table02_2");
            case 727 -> TileManager.getTile("table02_3");
            case 733 -> TileManager.getTile("table03_1");
            case 734 -> TileManager.getTile("table03_2");
            case 735 -> TileManager.getTile("table03_3");
            case 858 -> TileManager.getTile("jar01");
            case 859 -> TileManager.getTile("jar02");
            case 184 -> TileManager.getTile("fence_x");
            case 176 -> TileManager.getTile("fence_y");
            case 178 -> TileManager.getTile("fence_top_left");
            case 179 -> TileManager.getTile("fence_top_right");
            case 187 -> TileManager.getTile("fence_bot_right");
            case 186 -> TileManager.getTile("fence_bot_left");
            case 180 -> TileManager.getTile("fence_end_left");
            case 188 -> TileManager.getTile("fence_end_right");
            case 177 -> TileManager.getTile("fence_end_top");
            case 328 -> TileManager.getTile("stair_top_left");
            case 330 -> TileManager.getTile("stair_top_right");
            case 336 -> TileManager.getTile("stair_mid_left");
            case 337 -> TileManager.getTile("stair_mid_cen");
            case 338 -> TileManager.getTile("stair_mid_right");
            case 344 -> TileManager.getTile("stair_bot_left");
            case 345 -> TileManager.getTile("stair_bot_cen");
            case 346 -> TileManager.getTile("stair_bot_right");
            case 503 -> TileManager.getTile("player_house_door01");
            case 511 -> TileManager.getTile("player_house_door02");
            case 880 -> TileManager.getTile("straws01");
            case 881 -> TileManager.getTile("straws02");
            case 888 -> TileManager.getTile("straws03");
            case 889 -> TileManager.getTile("straws04");
            case 896 -> TileManager.getTile("straws05");
            case 897 -> TileManager.getTile("straws06");
            case 375 -> TileManager.getTile("shop_door01");
            case 383 -> TileManager.getTile("shop_door02");
            case 50 -> TileManager.getTile("stone_house_door01");
            case 58 -> TileManager.getTile("stone_house_door02");
            case 660 -> TileManager.getTile("stone_house_tag");
            case 884 -> TileManager.getTile("barrel01");
            case 885 -> TileManager.getTile("barrel02");
            case 892 -> TileManager.getTile("barrel03");
            case 893 -> TileManager.getTile("barrel04");
            case 900 -> TileManager.getTile("barrel05");
            case 901 -> TileManager.getTile("barrel06");
            case 597 -> TileManager.getTile("window01");
            case 605 -> TileManager.getTile("window02");
            case 230 -> TileManager.getTile("mission_board01");
            case 231 -> TileManager.getTile("mission_board02");
            case 238 -> TileManager.getTile("mission_board03");
            case 239 -> TileManager.getTile("mission_board04");
            case 235 -> TileManager.getTile("sign01");
            case 229 -> TileManager.getTile("sign02");
            case 237 -> TileManager.getTile("sign03");
            case 228 -> TileManager.getTile("post_box");
            case 293 -> TileManager.getTile("not_use");
            default -> null;
        };
    }
}
